In [4]:
import torch



In [5]:
torch.__version__

'2.5.1+cpu'

In [6]:
import numpy as np

In [10]:
lst = [3,4,5,6]
print(lst)
arr = np.array(lst)
print(arr)

[3, 4, 5, 6]
[3 4 5 6]


In [8]:
arr.dtype

dtype('int64')

## Convert Numpy to Pytorch Tensors

In [16]:
tensors = torch.from_numpy(arr)
print(tensors)
print(tensors.dtype)

tensor([3, 4, 5, 6])
torch.int64


In [19]:
### Indexing similar to numpy
print(tensors[:2])
print(tensors[0])
print(tensors[0:4])


tensor([3, 4])
tensor(3)
tensor([3, 4, 5, 6])


In [20]:
tensors[3] = 100
print(arr,tensors)

[  3   4   5 100] tensor([  3,   4,   5, 100])


In [21]:
### To prevent array and tensor from saving in the same memory location
tensors_new = torch.tensor(arr)
tensors_new

tensor([  3,   4,   5, 100])

In [22]:
tensors_new[3] = 200
print(arr)
print(tensors)
print(tensors_new)

[  3   4   5 100]
tensor([  3,   4,   5, 100])
tensor([  3,   4,   5, 200])


In [25]:
torch.zeros(2,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [26]:
torch.ones(3,3,dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

## Arithmetic Operations

In [27]:
arr0 = np.arange(0,15).reshape(5,3)
arr0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
tensors0 = torch.tensor(arr0)
tensors0

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [30]:
tensors1 = torch.tensor(np.arange(100,110).reshape(5,2))
tensors1

tensor([[100, 101],
        [102, 103],
        [104, 105],
        [106, 107],
        [108, 109]])

In [31]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [32]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [35]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [36]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [37]:
torch.add(a,b).sum()

tensor(27.)

## Multiplication and Dot Product

In [38]:
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [39]:
x.mul(y)

tensor([12., 20., 30.])

In [40]:
x.dot(y)

tensor(62.)

In [42]:
### Matrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [43]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [44]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [45]:
x@y

tensor([[55., 53.],
        [90., 92.]])